- name: add postgresql repository
  become: yes
  dnf:
    name: https://download.postgresql.org/pub/repos/yum/10/fedora/fedora-28-x86_64/pgdg-fedora10-10-4.noarch.rpm
    state: installed

- name: install postgresql 10 server
  dnf:
    name: [
      'python-devel',
      'postgresql10-server',
      'postgresql10',
      'postgresql10-contrib',
      'postgresql10-devel',
      'postgresql10-libs',
      'python-psycopg2'
    ]
    state: installed
  become: true

- name: init postgresql server
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb creates=/var/lib/pgsql/10/data/pg_hba.conf
  become: yes

- name: copy postgresql config
  template: src=templates/postgres/pg_hba.conf.j2 dest=/var/lib/pgsql/10/data/pg_hba.conf
  become: yes
  become_user: postgres

- name: adding custom settings
  shell: echo "myapp.userid='1'" >> /var/lib/pgsql/10/data/postgresql.conf
  become: yes

- name: open postgres for external connections
  when: API_ENV_TYPE=="local"
  lineinfile: path=/var/lib/pgsql/10/data/postgresql.conf regexp='^#listen_addresses' line="listen_addresses = '*'"
  become: true
  become_user: postgres

- name: enable and reload postgresql server
  service: name=postgresql-10 enabled=yes state=reloaded
  become: true
