- name: install redis server
  dnf: name=supervisor state=installed
  become: yes

- name: enabling supervisor server
  service: name=supervisord enabled=yes
  become: yes

- name: stopping supervisor server
  service: name=supervisord enabled=yes state=stopped
  become: yes

- name: generate supervisor.conf
  template:
    src: templates/supervisor/supervisord.conf.j2
    dest: /etc/supervisord.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: generate mcod.ini
  template: src=templates/supervisor/mcod.ini.j2 dest=/etc/supervisord.d/mcod.ini owner=root group=root mode=0644
  become: yes

- name: chown /var/run/supervisor to vagrant group
  file:
    path: /var/run/supervisor
    owner: root
    group: vagrant
  become: yes

- name: starting supervisor server
  service: name=supervisord state=started
  become: yes